### PR TITLE
Removes transmisogynist wording from code of conduct

### PR DESCRIPTION
**Pull request by mknadler**
As per https://github.com/WomenWhoCode/guidelines-resources/issues/12.

### CODE REVIEW

**Comment by allypalanzi** [comment]
:+1:

**Comment by aworkinglibrary** [comment]
:+1:

**Comment by KawaiiNerd82** [comment]
Love it!

**Comment by antislice** [comment]
:+1: 
WWC HQ + advisors are actively working on the code of conduct wording, including this part. Thanks for bringing it back to our attention, and I'm sorry it took this long to address it. @sursh @carobrwn

**Pull request merged**
